// Chat — sample inbox data matching the "Inbox D — Combined" design.
// Replace with a real Netlify function + Supabase query when the chat
// backend lands; the UI reads only from these shapes.

import type { ChatThread } from "./types";

// Relative timestamps are pre-baked as display strings in `at`; updatedAt
// is a real ISO so sort order works. (When wired to a backend, format
// `at` from updatedAt instead.)
export const SAMPLE_THREADS: ChatThread[] = [
  {
    id: "wo-2026-0418",
    kind: "workorder",
    title: "WO-2026-0418 · Ice maker",
    subtitle: "SDI 4287 · Mansfield, TX",
    scope: { kind: "workorder", refId: "WO-2026-0418" },
    participantUserIds: ["u-sarah", "u-me"],
    external: false,
    pinned: false,
    needsYou: true,
    status: { kind: "warn", label: "Needs info" },
    lastMessage: {
      fromUserId: "u-sarah",
      text: "GM Sarah Chen: Posted the warranty doc — Penguin says they'll honor it.",
      at: "11:42a",
    },
    unreadCount: 0,
    mentionedCount: 0,
    updatedAt: "2026-05-24T11:42:00Z",
  },
  {
    id: "sub-safety-3961",
    kind: "submission",
    title: "Safety Check · SDI 3961",
    subtitle: "Burleson, TX · Resubmitted",
    scope: { kind: "submission", refId: "sub-3961" },
    participantUserIds: ["u-priya", "u-me"],
    external: false,
    pinned: false,
    needsYou: true,
    status: { kind: "review", label: "Awaiting review" },
    lastMessage: {
      fromUserId: "u-priya",
      text: "GM Priya Mehta: Here's the dusk shot. Top-right segment is dead, the rest flickers.",
      at: "8:54p",
    },
    unreadCount: 0,
    mentionedCount: 0,
    updatedAt: "2026-05-23T20:54:00Z",
  },
  {
    id: "dm-linda",
    kind: "direct",
    title: "SDO Linda Chow",
    subtitle: "",
    participantUserIds: ["u-linda", "u-me"],
    external: false,
    pinned: false,
    needsYou: false,
    lastMessage: {
      fromUserId: "u-linda",
      text: "Got 5 min after lunch? Want to talk about the Crowley resubmission.",
      at: "10:12a",
    },
    unreadCount: 1,
    mentionedCount: 0,
    updatedAt: "2026-05-24T10:12:00Z",
  },
  {
    id: "bc-region14-weekly",
    kind: "broadcast",
    title: "Region 14 · Weekly note",
    subtitle: "",
    participantUserIds: [],
    external: false,
    pinned: false,
    needsYou: false,
    fromLabel: "From RVP Janelle Aoki",
    lastMessage: {
      fromUserId: "u-janelle",
      text: "Quick thanks to District 14B — best week-over-week move in the region.",
      at: "7:30a",
    },
    unreadCount: 0,
    mentionedCount: 0,
    updatedAt: "2026-05-24T07:30:00Z",
  },
  {
    id: "grp-d14b-gms",
    kind: "group",
    title: "District 14B · GMs",
    subtitle: "8 members",
    participantUserIds: ["u-sarah", "u-priya", "u-diego", "u-me"],
    external: false,
    pinned: false,
    needsYou: false,
    memberCount: 8,
    memberInitials: ["SC", "M"],
    lastMessage: {
      fromUserId: "u-diego",
      text: "Diego Alvarez: Anyone tried that new lid SKU for the large cups?",
      at: "Yesterday",
    },
    unreadCount: 3,
    mentionedCount: 0,
    updatedAt: "2026-05-23T16:00:00Z",
  },
  {
    id: "grp-region14-dos",
    kind: "group",
    title: "Region 14 · DOs",
    subtitle: "4 members",
    participantUserIds: ["u-heath", "u-tyler", "u-me"],
    external: false,
    pinned: false,
    needsYou: false,
    memberCount: 4,
    memberInitials: ["HF", "TB"],
    lastMessage: {
      fromUserId: "u-tyler",
      text: "Tyler Brooks: Pushing the ramp doc review to Thursday.",
      at: "Mon",
    },
    unreadCount: 2,
    mentionedCount: 0,
    updatedAt: "2026-05-19T09:00:00Z",
  },
];
