// netlify/functions/_lib/ciPatterns.js
//
// Compact, server-side copy of the Culture Index pattern definitions, used to
// GROUND the DO Playbook coaching prompt. We keep this server-authoritative
// (rather than trusting client-supplied text) so the model can only coach from
// the real definitions. The rich, UI-facing version lives at
// src/modules/culture-index/patterns.ts — keep the two in rough sync; this one
// only needs the coaching essentials.

export const CI_PATTERNS = {
  daredevil: { name: "Daredevil", essence: "Fearless, unconventional, take-charge risk-taker who craves autonomy and lives in the future.", strengths: "Decisive under pressure; ingenious; delegates freely; motivates people.", watchouts: "Ignores rules/detail; poor follow-through; resists structure.", motivators: "Independence, financial rewards, goal-setting.", style: "Blunt, conceptual; delegating manager; needs unstructured, fast, changing work." },
  enterpriser: { name: "Enterpriser", essence: "Assertive, analytical self-starter focused on attaining goals fast, then moving on.", strengths: "Goal attainment; troubleshooting; drives change; high standards.", watchouts: "Bored by maintenance; blunt/cold; can neglect micro-detail; combative if over-ruled.", motivators: "Independence, financial rewards, learning, goals.", style: "Factual, authoritative, email-preferred; authoritarian; structured & fast." },
  philosopher: { name: "Philosopher", essence: "Private, independent conceptual thinker who prefers to work alone and dislikes rules/authority.", strengths: "Original solutions; independent; deep thinker.", watchouts: "Procrastinates without deadlines; not a team player; aloof; resists structure.", motivators: "Freedom/independence, private rewards.", style: "Cerebral, sometimes vague; autocratic; loose, project-oriented work." },
  trailblazer: { name: "Trailblazer", essence: "Competitive, driven self-starter who thrives on winning, mentoring, and constant change.", strengths: "Competitive drive; mentors people; thrives on change; influences and wins.", watchouts: "Short attention/priority-hopping; impatient; disengages when bored.", motivators: "Independence, financial rewards, public recognition.", style: "Persuasive; mentoring manager, delegates; fast, changing work." },
  architect: { name: "Architect", essence: "Proactive, take-charge builder of systems and processes; a well-calculated risk-taker.", strengths: "Builds systems; high standards; relentless follow-through; drives results.", watchouts: "Slow to delegate until trust earned; blunt; impatient; under-communicates intent.", motivators: "Independence, financial rewards, goal-setting.", style: "Commanding, detailed; authoritarian; precise, structured, fast." },
  "technical-expert": { name: "Technical Expert", essence: "Impatient, accuracy-driven expert who corrects others as a duty and needs proof to be convinced.", strengths: "Accuracy/compliance; system mastery; problem diagnosis; by-the-book reliability.", watchouts: "Micromanages; won't delegate; skeptical/slow to trust; can seem condescending.", motivators: "Independence, private recognition, specialized development.", style: "Factual, quick, data-heavy; instructional but micromanaging; structured, personal space." },
  scholar: { name: "Scholar", essence: "Independent, analytical deep-thinker who is knowledge- and quality-driven.", strengths: "Analytical depth; independent problem-solving; quality; masters new systems.", watchouts: "Over-analyzes vs. acts; low people orientation; disengages from routine; low urgency.", motivators: "Intellectual challenge, mastery, private recognition.", style: "Reserved, precise, written; autonomous; depth over speed." },
  specialist: { name: "Specialist", essence: "Guarded, hard-working perfectionist; highly critical in their expertise; deeply loyal once trust is earned.", strengths: "Relentless accuracy; quality; work ethic; reliability.", watchouts: "Harsh/critical; risk-averse (freezes on the novel); thin-skinned; poor people-manager.", motivators: "Independent work, personal space, private recognition.", style: "Fast, factual, data-filled; manages process not people; fast, personal space." },
  craftsman: { name: "Craftsman", essence: "Reactive, patient, dependable creature of habit who excels at consistent, single-focus work.", strengths: "Consistency/reliability; patience with repetitive tasks; follows process; accountable.", watchouts: "Struggles with fast pace/urgency; avoids confrontation; resists change; not a natural leader; lower energy.", motivators: "Sincere rewards, personal space, private recognition.", style: "Detailed, casual; task management, no reports; stable, consistent, harmonic." },
  persuader: { name: "Persuader", essence: "Fast, enthusiastic relationship-builder who wins people over and thinks out loud.", strengths: "Motivates people; customer rapport; drives sales/persuasion; energy under pressure.", watchouts: "Weak follow-through/documentation; over-promises; avoids discipline.", motivators: "Independence/income, praise in front of others.", style: "Effervescent, fast; motivational/lenient, needs to delegate; busy, needs detail support." },
  rainmaker: { name: "Rainmaker", essence: "Assertive, outgoing deal-maker who reads people brilliantly and thrives on relationships.", strengths: "Relationships/community; selling; persuasion; morale.", watchouts: "Unreliable follow-through; poor organizer; imprecise with facts; needs structure around them.", motivators: "Independence, financial rewards, public recognition.", style: "Enthusiastic, quick; motivational/lenient; fast, constant change, needs detail help." },
  influencer: { name: "Influencer", essence: "Persuasive, people-connecting motivator who rallies a team and reads a room, with a bit more structure than a Rainmaker.", strengths: "Rallies/motivates people; customer warmth; communication; adaptable with people.", watchouts: "Consistency of standards (may prioritize being liked); detail follow-through.", motivators: "Social interaction, recognition.", style: "Warm, persuasive; shift-lead/assistant fit; needs clear standards." },
  debater: { name: "Debater", essence: "Friendly, persuasive, laid-back communicator who likes to trade ideas and (gently) argue.", strengths: "Liaison/communication; patience with people; morale; persuasion.", watchouts: "Argumentative/non-conformist; avoids confrontation/discipline; socially distracted; needs direction.", motivators: "Social interaction, financial rewards, public recognition.", style: "Easy-going, conceptual; needs direction, facilitates through others; steady, needs detail help." },
  socializer: { name: "Socializer", essence: "The most people-driven pattern — flamboyant, warm, happiest surrounded by people.", strengths: "Customer experience/hospitality; morale; welcoming presence; selling.", watchouts: "Distractible; poor follow-through/documentation; needs imposed structure; avoids detail.", motivators: "Social interaction, status/money, praise in front of others.", style: "Gregarious, colorful; likes to delegate; easy-going, people-rich, stable." },
  administrator: { name: "Administrator", essence: "Optimistic, organized team-builder who teaches new people and keeps things tidy.", strengths: "Trains/onboards; organizes; team leadership; morale.", watchouts: "Dislikes tedious technical detail; needs recognition; can be distracted; occasional sharp comments.", motivators: "Reinforcement in front of others, bonuses, titles.", style: "Fast, detailed; teaches new employees; neat, group-oriented." },
  coordinator: { name: "Coordinator", essence: "Optimistic, animated organizer of people and tasks who runs on rules and structure.", strengths: "Coordinates people/tasks/schedules; communicates; detail with structure; tidy.", watchouts: "Defensive when corrected; needs rules & direction; risk-averse; not big-picture strategy.", motivators: "Social interaction, position titles, public recognition.", style: "Fast, detailed; instructional, task-oriented; orderly, change-required." },
  facilitator: { name: "Facilitator", essence: "Polite, methodical, single-focus team player who executes tasks exactly and reliably.", strengths: "Methodical execution; follows procedures exactly; reliable; good listener/support.", watchouts: "Rattled by change/surprise; struggles with fast pace; over-commits; avoids people-management.", motivators: "Social interaction, constant reassurance, recognition.", style: "Detailed, casual; needs direction, task management; orderly, stable." },
  operator: { name: "Operator", essence: "Easy-going, heads-down processor of tasks who prizes stability and does repetitive work seamlessly.", strengths: "Reliable repetitive-task execution; detail/accuracy; by-the-book compliance; steady/loyal.", watchouts: "Dislikes multitasking/fast pace; resists change; low people orientation; needs defined duties.", motivators: "Risk-free, predictability, private recognition.", style: "Slow, factual; needs direction, task management; systematic, stable." },
  traditionalist: { name: "Traditionalist", essence: "Due-diligent, history-minded worrier obsessed with getting it right and following the Book.", strengths: "Procedural accuracy/compliance; work ethic; institutional knowledge; supportive.", watchouts: "Perfectionism can miss deadlines; worry/thin skin; struggles with change & pace; avoids confrontation.", motivators: "Risk-free, constant reassurance, private recognition.", style: "Factual, lengthy; needs direction, task management; systematic, stable." },
  chameleon: { name: "Chameleon", essence: "All behavioral drives elevated and balanced — a highly adaptable person who flexes to the situation.", strengths: "Adaptability across situations; can lead, serve, and multitask at once; high capacity.", watchouts: "Adaptability can tip into people-pleasing or inconsistent standards; over-extension/burnout.", motivators: "Varies with context.", style: "Flexes to context; best paired with a firm anchor on standards." },
  avoidant: { name: "Avoidant", essence: "Not a personality — a data-quality flag (invalid/avoidant survey).", strengths: "", watchouts: "Do not use for personality-fit decisions; re-administer.", motivators: "", style: "N/A." },
};

export function normalizeTrait(s) {
  return String(s || "").toLowerCase().replace(/[^a-z]/g, "");
}

const BY_NAME = new Map(
  Object.entries(CI_PATTERNS).map(([id, p]) => [normalizeTrait(p.name), { id, ...p }]),
);

export function ciPatternForTrait(trait) {
  if (!trait) return null;
  return BY_NAME.get(normalizeTrait(trait)) || null;
}
